#line 1 "./S1/compiler_lexer.cpp"
#include "S1.hpp"
#include "compiler_parser.hpp"
#ifndef YY_NO_UNISTD_H
#define YY_NO_UNISTD_H
#endif

#line 8 "./S1/compiler_lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define S1_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer S1_create_buffer
#endif

#ifdef yy_delete_buffer
#define S1_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer S1_delete_buffer
#endif

#ifdef yy_scan_buffer
#define S1_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer S1_scan_buffer
#endif

#ifdef yy_scan_string
#define S1_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string S1_scan_string
#endif

#ifdef yy_scan_bytes
#define S1_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes S1_scan_bytes
#endif

#ifdef yy_init_buffer
#define S1_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer S1_init_buffer
#endif

#ifdef yy_flush_buffer
#define S1_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer S1_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define S1_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state S1_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define S1_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer S1_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define S1push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state S1push_buffer_state
#endif

#ifdef yypop_buffer_state
#define S1pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state S1pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define S1ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack S1ensure_buffer_stack
#endif

#ifdef yylex
#define S1lex_ALREADY_DEFINED
#else
#define yylex S1lex
#endif

#ifdef yyrestart
#define S1restart_ALREADY_DEFINED
#else
#define yyrestart S1restart
#endif

#ifdef yylex_init
#define S1lex_init_ALREADY_DEFINED
#else
#define yylex_init S1lex_init
#endif

#ifdef yylex_init_extra
#define S1lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra S1lex_init_extra
#endif

#ifdef yylex_destroy
#define S1lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy S1lex_destroy
#endif

#ifdef yyget_debug
#define S1get_debug_ALREADY_DEFINED
#else
#define yyget_debug S1get_debug
#endif

#ifdef yyset_debug
#define S1set_debug_ALREADY_DEFINED
#else
#define yyset_debug S1set_debug
#endif

#ifdef yyget_extra
#define S1get_extra_ALREADY_DEFINED
#else
#define yyget_extra S1get_extra
#endif

#ifdef yyset_extra
#define S1set_extra_ALREADY_DEFINED
#else
#define yyset_extra S1set_extra
#endif

#ifdef yyget_in
#define S1get_in_ALREADY_DEFINED
#else
#define yyget_in S1get_in
#endif

#ifdef yyset_in
#define S1set_in_ALREADY_DEFINED
#else
#define yyset_in S1set_in
#endif

#ifdef yyget_out
#define S1get_out_ALREADY_DEFINED
#else
#define yyget_out S1get_out
#endif

#ifdef yyset_out
#define S1set_out_ALREADY_DEFINED
#else
#define yyset_out S1set_out
#endif

#ifdef yyget_leng
#define S1get_leng_ALREADY_DEFINED
#else
#define yyget_leng S1get_leng
#endif

#ifdef yyget_text
#define S1get_text_ALREADY_DEFINED
#else
#define yyget_text S1get_text
#endif

#ifdef yyget_lineno
#define S1get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno S1get_lineno
#endif

#ifdef yyset_lineno
#define S1set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno S1set_lineno
#endif

#ifdef yyget_column
#define S1get_column_ALREADY_DEFINED
#else
#define yyget_column S1get_column
#endif

#ifdef yyset_column
#define S1set_column_ALREADY_DEFINED
#else
#define yyset_column S1set_column
#endif

#ifdef yywrap
#define S1wrap_ALREADY_DEFINED
#else
#define yywrap S1wrap
#endif

#ifdef yyalloc
#define S1alloc_ALREADY_DEFINED
#else
#define yyalloc S1alloc
#endif

#ifdef yyrealloc
#define S1realloc_ALREADY_DEFINED
#else
#define yyrealloc S1realloc
#endif

#ifdef yyfree
#define S1free_ALREADY_DEFINED
#else
#define yyfree S1free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define S1wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[288] =
    {   0,
        0,    0,    0,    0,    0,    0,   99,   97,    1,    2,
       86,   97,   97,   85,   89,   97,   47,   48,   83,   81,
       53,   82,   54,   84,   96,   56,   57,   70,   80,   71,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   51,   52,   90,   49,
       88,   50,   87,    5,    6,    5,    9,   10,    9,   67,
        0,   94,    0,    0,    0,    0,   76,    0,   65,    0,
       78,    0,    0,   74,   58,   72,   59,   73,   95,    8,
        4,    3,   75,   95,   96,    0,    0,   55,   62,   68,
       66,   69,   63,   92,   92,   92,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   22,   27,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   46,
       79,   77,   64,    7,   11,    0,   94,    0,    0,    0,
        0,    0,   93,    0,    0,    0,    0,   94,    0,   95,
        3,   95,   95,   91,   60,   61,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   25,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
        0,    0,    0,    0,   93,    0,    0,   93,    0,   44,
       92,   37,   29,   92,   92,   92,   23,   92,   92,   92,
       42,   92,   92,   92,   43,   41,   92,   92,   92,   38,

       92,   17,   92,    0,    0,    0,   31,   92,   92,   92,
       15,   39,   92,   45,   92,   92,   92,   92,   92,   92,
       92,   92,   24,    0,    0,    0,   92,   92,   92,   92,
       16,   33,   28,   92,   34,   92,   92,   92,    0,    0,
        0,   92,   92,   30,   26,   92,   92,   92,   92,    0,
       12,    0,   92,   32,   92,   92,   92,   18,   14,    0,
       92,   92,   40,   21,   92,   92,    0,   92,   36,   92,
       92,    0,   35,   92,   92,    0,   92,   92,    0,   92,
       19,    0,   92,   13,   92,   20,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   33,
       33,   39,   40,   41,   42,   43,   44,   33,   45,   46,
       47,   48,   49,   50,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   33,   61,   62,   63,   64,
       65,   33,   33,   66,   67,   68,   69,   70,   71,   33,
       72,   73,   74,   75,   76,   77,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[78] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    1,    5,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    6,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[303] =
    {   0,
        0,    0,   75,   76,   77,   78,  380,  958,  958,  958,
      357,   77,   61,  353,   86,   80,  958,  958,  352,   77,
      958,   82,  355,   90,   93,  353,  958,   79,  298,   83,
       83,   71,  102,  101,  107,  100,  108,  103,  143,  131,
      128,  147,  153,  163,  162,  190,  263,  958,  274,  958,
       70,  958,  958,  958,  958,  227,  958,  958,  195,  958,
      122,  958,  179,   99,  151,  149,  958,  148,  958,  125,
      958,  126,  183,  958,  958,  958,  958,  958,  188,  958,
      958,    0,  958,  190,  202,  182,    0,  958,  182,  958,
      958,  958,  161,    0,  175,  219,  213,  218,  222,  220,

      217,  224,  228,  225,  247,  241,  233,  244,  260,  273,
      275,  263,  278,  285,  290,  286,  291,  287,  300,  958,
      958,  958,  958,  958,  958,  289,  292,  304,  239,  305,
      304,  305,  958,  339,  318,  354,  340,  345,  358,  958,
        0,  340,  958,  116,  958,  958,  347,  353,  350,  361,
      356,  355,  384,  366,  377,  371,  385,  392,  401,  411,
      412,  415,  419,  420,  416,  422,  437,  438,  436,  447,
      189,  201,  391,  373,  441,  471,  449,  460,  470,  465,
      472,  475,  476,  483,  484,  486,  477,  492,  487,  497,
      488,  502,  512,  515,  499,  511,  531,  524,  538,  527,

      551,  553,  555,  510,  519,  518,  543,  552,  558,  569,
      559,  581,  587,  582,  594,  590,  597,  601,  609,  611,
      619,  629,  599,  532,  560,   88,  622,  604,  635,  647,
      603,  640,  648,  653,  650,  654,  660,  659,  644,  654,
      662,  665,  694,  672,  675,  696,  700,  690,  701,  669,
      958,  690,  717,  714,  719,  720,  718,  722,  958,  709,
      740,  745,  742,  746,  762,  763,  723,  768,  761,  765,
      766,  750,  781,  783,  782,  760,  797,  789,  777,  807,
      791,  793,  817,  958,  823,  809,  958,  881,  887,  893,
      899,  902,  906,  912,  918,  924,  930,  936,  109,  940,

      945,  951
    } ;

static const flex_int16_t yy_def[303] =
    {   0,
      287,    1,  288,  288,  289,  289,  287,  287,  287,  287,
      287,  290,  287,  287,  287,  291,  287,  287,  287,  287,
      287,  287,  287,  287,  292,  287,  287,  287,  287,  287,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      290,  287,  294,  287,  287,  287,  287,  295,  287,  296,
      287,  291,  297,  287,  287,  287,  287,  287,  287,  287,
      287,  298,  287,  287,  292,  292,  299,  287,  287,  287,
      287,  287,  287,  300,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  287,
      287,  287,  287,  287,  287,  290,  290,  294,  287,  287,
      287,  295,  287,  301,  296,  302,  291,  291,  297,  287,
      298,  287,  287,  299,  287,  287,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      287,  287,  287,  295,  295,  301,  296,  296,  302,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,

      293,  293,  293,  287,  287,  287,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  287,  287,  287,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  287,  287,
      287,  293,  293,  293,  293,  293,  293,  293,  293,  287,
      287,  287,  293,  293,  293,  293,  293,  293,  287,  287,
      293,  293,  293,  293,  293,  293,  287,  293,  293,  293,
      293,  287,  293,  293,  293,  287,  293,  293,  287,  293,
      293,  287,  293,  287,  293,  293,    0,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287
    } ;

static const flex_int16_t yy_nxt[1036] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   38,   38,   40,   38,   41,   38,   42,   43,
       44,   45,   38,   46,   38,   38,   47,    8,   48,   49,
       38,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       38,   40,   38,   41,   38,   42,   43,   44,   45,   38,
       46,   38,   38,   50,   51,   52,   53,   55,   55,   58,
       58,   62,   59,   59,   64,   94,   56,   56,   62,   75,
       68,  122,   65,   69,   70,   80,   77,   94,   76,   89,

       90,   81,   66,   78,   92,   93,   82,   71,   84,   97,
       85,   83,   64,  144,   94,   94,   94,   94,   87,   96,
       65,   94,   94,  104,   63,   98,   62,   73,  101,   66,
       87,  106,   99,  133,   62,  129,   97,  105,  241,  100,
       87,  102,   94,  103,  123,   94,   96,   87,   87,   87,
       87,  104,  133,   98,   87,   87,  101,   94,  109,  106,
       99,   94,  129,   87,  105,  110,  100,   94,  102,   63,
      103,  107,  136,   73,  111,   87,   94,   94,   87,  108,
      112,   61,  146,  127,  113,   72,  109,  130,  131,   94,
       87,  138,  110,  115,   87,  134,  114,  287,  117,  107,

       87,  116,  111,  145,   94,   79,  108,  142,  112,   87,
       87,  125,  113,  118,  130,  131,  140,   84,  143,   85,
      119,  115,   87,  114,  204,  117,  128,   94,  116,   87,
      139,   94,   94,   94,   94,  205,   94,   87,   94,   94,
      148,  118,   94,  124,  140,  153,  143,   94,  119,   87,
      147,  204,  149,  151,  155,   94,  152,  150,   94,  156,
       87,   94,  205,  154,   87,   87,   87,   87,  148,   87,
      171,   87,   87,  153,   94,   87,  158,   94,  147,  149,
       87,  151,  155,  152,  150,  157,  156,   94,   87,   94,
      154,   87,   94,   62,   87,  121,   62,  162,  171,   94,

       94,   94,  159,  158,   94,   94,   61,   87,  127,  133,
       87,  120,  157,  160,   94,  161,  164,  168,  169,   91,
       87,  165,   87,  163,  162,   87,  133,  167,  166,  159,
      172,  170,   87,   87,   87,  173,   63,   87,   87,   63,
      160,  132,  161,  175,  164,  168,  169,   87,   62,  165,
      163,  128,  134,   62,  167,  166,  135,  142,  172,  170,
       72,   94,  178,  173,   94,  136,  138,   94,  143,   94,
       94,   88,   79,   74,   67,   94,  181,  133,   60,  287,
       94,  287,  180,  287,  182,   94,  176,   73,  183,  287,
      184,   94,   73,  187,   87,  185,  143,   87,   94,   94,

       87,  179,   87,   87,  181,  139,   94,  186,   87,  180,
      189,  182,  190,   87,  188,   94,  183,  184,   87,  191,
      134,  187,  185,  287,   87,   94,   94,  206,  192,   94,
       94,   87,   87,   94,   94,  186,   94,  189,  287,   87,
      190,  188,  193,  195,  287,  133,  196,  191,   87,  199,
       94,   94,   94,  194,  206,  198,  192,  133,   87,   87,
      197,   94,   87,   87,  200,  201,   87,   87,  133,   87,
      193,  195,  135,  132,  196,  175,  202,  199,  178,   94,
      194,  203,  198,   87,   87,   87,   94,  197,  134,   94,
       94,   94,  200,  201,   87,  287,  136,   94,   94,  287,

       94,   94,   94,  202,  287,  207,   94,  136,  203,  208,
      287,   94,   87,   94,  212,  209,   94,  179,  176,   87,
      213,  287,   87,   87,   87,   94,   94,  210,  211,   94,
       87,   87,  207,   87,   87,   87,  214,  208,   94,   87,
      215,   94,  212,  209,   87,   94,   87,  226,  213,   87,
      224,  287,   94,  216,  210,  211,  217,   94,   87,   87,
      225,  219,   87,  214,  218,   94,   94,   94,  215,   94,
      239,   87,   94,   94,   87,  226,  287,  224,   87,  220,
      216,  221,  223,   94,  217,   87,  240,  225,  287,  219,
       87,  218,  227,  222,  228,   94,   94,  239,   87,   87,

       87,   94,   87,  229,   94,   87,   87,  220,   94,  221,
      223,   94,  230,   94,  240,   94,   87,   94,   94,  227,
      222,  228,  287,   94,  287,   94,  232,  233,   87,   87,
      229,  234,  287,   94,   87,  235,   94,   87,  231,  287,
      230,   87,  236,   94,   87,  243,   87,  287,   87,   94,
       87,   87,  242,  232,   94,  233,   87,  237,   87,  234,
      238,   94,   94,  235,   94,  231,   87,   94,   94,   87,
      236,  250,  243,   94,   94,  244,   87,  245,  287,   94,
      242,  251,   87,  248,  237,  252,   94,   87,  238,   94,
      247,  246,  287,  249,   87,   87,  259,   87,  287,  250,

       87,   87,  244,  253,   94,  245,   87,   87,   94,  251,
       94,  248,   87,  252,   94,   94,  287,  247,  246,   87,
      249,  254,   87,  255,  259,  257,  260,  256,   94,  287,
      253,   94,   94,   94,   94,  258,   94,   87,  287,  287,
      267,   87,  262,   87,  261,  264,  263,   87,   87,  254,
      265,  255,  257,  260,   94,  256,   94,  266,  272,   94,
       94,   87,  258,  268,   87,   87,   87,   87,  267,   87,
      262,  269,  261,  264,  263,   94,   94,   94,  265,   94,
       94,  287,   94,  287,  266,  272,  271,   87,  274,   87,
      276,  268,   87,   87,  273,   94,   94,   94,  279,  269,

      270,  287,  287,   94,  282,   94,  275,  278,   87,   87,
       87,   94,   87,   87,  271,   87,  274,  276,  277,  281,
      284,   94,  273,   94,  280,  279,  287,  270,   87,   87,
       87,   94,  282,  275,  283,  278,   87,   94,   87,  287,
      287,  287,  287,  287,   87,  277,  287,  281,  284,  286,
      287,  287,  280,  285,   87,  287,   87,  287,  287,  287,
      287,  287,  283,  287,   87,  287,  287,  287,  287,  287,
       87,  287,  287,  287,  287,  287,  287,  286,  287,  287,
      285,   54,   54,   54,   54,   54,   54,   57,   57,   57,
       57,   57,   57,   61,   61,   61,   61,   61,   61,   72,

       72,   72,   72,   72,   72,   86,   86,   86,   95,  287,
       95,   95,  126,  126,  126,  126,  126,  126,  132,  132,
      132,  132,  132,  132,  135,  135,  135,  135,  135,  135,
      137,  137,  137,  137,  137,  137,  141,  287,  141,  141,
      141,  141,   94,  287,   94,  174,  174,  174,  174,  174,
      174,  177,  177,  177,  177,  177,  177,    7,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287
    } ;

static const flex_int16_t yy_chk[1036] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,    5,
        6,   12,    5,    6,   13,   32,    3,    4,   16,   20,
       15,   51,   13,   15,   15,   24,   22,   31,   20,   28,

       28,   24,   13,   22,   30,   30,   24,   15,   25,   32,
       25,   24,   13,  299,   36,   34,   33,   38,   32,   31,
       13,   35,   37,   36,   12,   33,   61,   16,   34,   13,
       31,   37,   33,   70,   72,   64,   32,   36,  226,   33,
       25,   35,   41,   35,   51,   40,   31,   36,   34,   33,
       38,   36,   68,   33,   35,   37,   34,   39,   40,   37,
       33,   42,   64,  144,   36,   41,   33,   43,   35,   61,
       35,   39,   70,   72,   42,   41,   45,   44,   40,   39,
       43,   63,   93,   63,   43,   73,   40,   65,   66,   95,
       39,   73,   41,   44,   42,   68,   43,   86,   45,   39,

       43,   44,   42,   89,   46,   79,   39,   84,   43,   45,
       44,   59,   43,   46,   65,   66,   79,   85,   84,   85,
       46,   44,   95,   43,  171,   45,   63,   97,   44,   86,
       73,  101,   98,   96,  100,  172,   99,   46,  102,  104,
       97,   46,  103,   56,   79,  101,   84,  107,   46,   85,
       96,  171,   98,   99,  103,  106,  100,   98,  108,  104,
       97,  105,  172,  102,  101,   98,   96,  100,   97,   99,
      129,  102,  104,  101,  109,  103,  106,  112,   96,   98,
      107,   99,  103,  100,   98,  105,  104,  110,  106,  111,
      102,  108,  113,  126,  105,   49,  127,  112,  129,  114,

      116,  118,  109,  106,  115,  117,  128,  109,  128,  132,
      112,   47,  105,  110,  119,  111,  114,  117,  118,   29,
      110,  115,  111,  113,  112,  113,  135,  116,  115,  109,
      130,  119,  114,  116,  118,  131,  126,  115,  117,  127,
      110,  134,  111,  134,  114,  117,  118,  119,  137,  115,
      113,  128,  132,  138,  116,  115,  136,  142,  130,  119,
      139,  147,  136,  131,  149,  135,  139,  148,  142,  152,
      151,   26,   23,   19,   14,  150,  148,  174,   11,    7,
      154,    0,  147,    0,  149,  156,  134,  137,  150,    0,
      151,  155,  138,  154,  147,  152,  142,  149,  153,  157,

      148,  136,  152,  151,  148,  139,  158,  153,  150,  147,
      156,  149,  157,  154,  155,  159,  150,  151,  156,  158,
      174,  154,  152,    0,  155,  160,  161,  173,  159,  162,
      165,  153,  157,  163,  164,  153,  166,  156,    0,  158,
      157,  155,  160,  162,    0,  175,  163,  158,  159,  166,
      169,  167,  168,  161,  173,  165,  159,  177,  160,  161,
      164,  170,  162,  165,  167,  168,  163,  164,  178,  166,
      160,  162,  179,  176,  163,  176,  169,  166,  179,  180,
      161,  170,  165,  169,  167,  168,  181,  164,  175,  182,
      183,  187,  167,  168,  170,    0,  177,  184,  185,    0,

      186,  189,  191,  169,    0,  181,  188,  178,  170,  184,
        0,  190,  180,  195,  189,  185,  192,  179,  176,  181,
      190,    0,  182,  183,  187,  196,  193,  186,  188,  194,
      184,  185,  181,  186,  189,  191,  192,  184,  198,  188,
      193,  200,  189,  185,  190,  197,  195,  206,  190,  192,
      204,    0,  199,  194,  186,  188,  197,  207,  196,  193,
      205,  199,  194,  192,  198,  201,  208,  202,  193,  203,
      224,  198,  209,  211,  200,  206,    0,  204,  197,  201,
      194,  202,  203,  210,  197,  199,  225,  205,    0,  199,
      207,  198,  208,  202,  209,  212,  214,  224,  201,  208,

      202,  213,  203,  210,  216,  209,  211,  201,  215,  202,
      203,  217,  213,  223,  225,  218,  210,  231,  228,  208,
      202,  209,    0,  219,    0,  220,  216,  217,  212,  214,
      210,  218,    0,  221,  213,  219,  227,  216,  215,    0,
      213,  215,  220,  222,  217,  228,  223,    0,  218,  229,
      231,  228,  227,  216,  232,  217,  219,  221,  220,  218,
      222,  230,  233,  219,  235,  215,  221,  234,  236,  227,
      220,  239,  228,  238,  237,  229,  222,  230,    0,  242,
      227,  240,  229,  237,  221,  241,  244,  232,  222,  245,
      236,  234,    0,  238,  230,  233,  250,  235,    0,  239,

      234,  236,  229,  242,  248,  230,  238,  237,  243,  240,
      246,  237,  242,  241,  247,  249,    0,  236,  234,  244,
      238,  243,  245,  246,  250,  248,  252,  247,  254,    0,
      242,  253,  257,  255,  256,  249,  258,  248,    0,    0,
      260,  243,  255,  246,  253,  257,  256,  247,  249,  243,
      258,  246,  248,  252,  261,  247,  263,  258,  267,  262,
      264,  254,  249,  261,  253,  257,  255,  256,  260,  258,
      255,  262,  253,  257,  256,  269,  265,  266,  258,  270,
      271,    0,  268,    0,  258,  267,  266,  261,  270,  263,
      272,  261,  262,  264,  268,  273,  275,  274,  276,  262,

      265,    0,    0,  278,  279,  281,  271,  275,  269,  265,
      266,  277,  270,  271,  266,  268,  270,  272,  274,  278,
      282,  280,  268,  286,  277,  276,    0,  265,  273,  275,
      274,  283,  279,  271,  280,  275,  278,  285,  281,    0,
        0,    0,    0,    0,  277,  274,    0,  278,  282,  285,
        0,    0,  277,  283,  280,    0,  286,    0,    0,    0,
        0,    0,  280,    0,  283,    0,    0,    0,    0,    0,
      285,    0,    0,    0,    0,    0,    0,  285,    0,    0,
      283,  288,  288,  288,  288,  288,  288,  289,  289,  289,
      289,  289,  289,  290,  290,  290,  290,  290,  290,  291,

      291,  291,  291,  291,  291,  292,  292,  292,  293,    0,
      293,  293,  294,  294,  294,  294,  294,  294,  295,  295,
      295,  295,  295,  295,  296,  296,  296,  296,  296,  296,
      297,  297,  297,  297,  297,  297,  298,    0,  298,  298,
      298,  298,  300,    0,  300,  301,  301,  301,  301,  301,
      301,  302,  302,  302,  302,  302,  302,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,

      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  287,  287,  287,  287
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "S1.lexer.lpp"
/* Copyright 2021 xensik. All rights reserved.
//
// Use of this source code is governed by a GNU GPLv3 license
// that can be found in the LICENSE file.
*/
#define YY_NO_INPUT 1
#define YY_NO_UNISTD_H 1



#line 975 "./S1/compiler_lexer.cpp"

#define INITIAL 0
#define COMMENT_BLOCK_STATE 1
#define DEVELOPER_BLOCK_STATE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 34 "S1.lexer.lpp"


#line 1238 "./S1/compiler_lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 288 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 287 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "S1.lexer.lpp"

	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 38 "S1.lexer.lpp"
{ (*pos)++; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "S1.lexer.lpp"

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "S1.lexer.lpp"
{ BEGIN(COMMENT_BLOCK_STATE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "S1.lexer.lpp"

	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 44 "S1.lexer.lpp"
{ (*pos)++; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "S1.lexer.lpp"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "S1.lexer.lpp"
{ BEGIN(DEVELOPER_BLOCK_STATE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "S1.lexer.lpp"

	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 49 "S1.lexer.lpp"
{ (*pos)++; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "S1.lexer.lpp"
{ BEGIN(INITIAL); }	
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 52 "S1.lexer.lpp"
{ return S1::parser::make_INCLUDE(); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 53 "S1.lexer.lpp"
{ return S1::parser::make_USINGTREE(); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "S1.lexer.lpp"
{ return S1::parser::make_ANIMTREE(); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "S1.lexer.lpp"
{ return S1::parser::make_ENDON(); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "S1.lexer.lpp"
{ return S1::parser::make_NOTIFY(); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "S1.lexer.lpp"
{ return S1::parser::make_WAIT(); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 58 "S1.lexer.lpp"
{ return S1::parser::make_WAITTILL(); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 59 "S1.lexer.lpp"
{ return S1::parser::make_WAITTILLMATCH(); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 60 "S1.lexer.lpp"
{ return S1::parser::make_WAITTILLFRAMEEND(); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "S1.lexer.lpp"
{ return S1::parser::make_WAITFRAME(); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 62 "S1.lexer.lpp"
{ return S1::parser::make_IF(); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 63 "S1.lexer.lpp"
{ return S1::parser::make_ELSE(); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 64 "S1.lexer.lpp"
{ return S1::parser::make_WHILE(); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "S1.lexer.lpp"
{ return S1::parser::make_FOR(); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 66 "S1.lexer.lpp"
{ return S1::parser::make_FOREACH(); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 67 "S1.lexer.lpp"
{ return S1::parser::make_IN(); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 68 "S1.lexer.lpp"
{ return S1::parser::make_SWITCH(); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 69 "S1.lexer.lpp"
{ return S1::parser::make_CASE(); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 70 "S1.lexer.lpp"
{ return S1::parser::make_DEFAULT(); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "S1.lexer.lpp"
{ return S1::parser::make_BREAK(); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "S1.lexer.lpp"
{ return S1::parser::make_CONTINUE(); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "S1.lexer.lpp"
{ return S1::parser::make_RETURN(); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "S1.lexer.lpp"
{ return S1::parser::make_THREAD(); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "S1.lexer.lpp"
{ return S1::parser::make_CHILDTHREAD(); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "S1.lexer.lpp"
{ return S1::parser::make_THISTHREAD(); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "S1.lexer.lpp"
{ return S1::parser::make_CALL(); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "S1.lexer.lpp"
{ return S1::parser::make_TRUE(); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "S1.lexer.lpp"
{ return S1::parser::make_FALSE(); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "S1.lexer.lpp"
{ return S1::parser::make_UNDEFINED(); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "S1.lexer.lpp"
{ return S1::parser::make_SIZE(); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "S1.lexer.lpp"
{ return S1::parser::make_GAME(); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "S1.lexer.lpp"
{ return S1::parser::make_SELF(); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "S1.lexer.lpp"
{ return S1::parser::make_ANIM(); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "S1.lexer.lpp"
{ return S1::parser::make_LEVEL(); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "S1.lexer.lpp"
{ return S1::parser::make_EMPTY_ARRAY(); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "S1.lexer.lpp"
{ return S1::parser::make_LPAREN(); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "S1.lexer.lpp"
{ return S1::parser::make_RPAREN(); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "S1.lexer.lpp"
{ return S1::parser::make_LBRACE(); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "S1.lexer.lpp"
{ return S1::parser::make_RBRACE(); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 91 "S1.lexer.lpp"
{ return S1::parser::make_LBRACKET(); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 92 "S1.lexer.lpp"
{ return S1::parser::make_RBRACKET(); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 93 "S1.lexer.lpp"
{ return S1::parser::make_COMMA(); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 94 "S1.lexer.lpp"
{ return S1::parser::make_DOT(); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 95 "S1.lexer.lpp"
{ return S1::parser::make_DOUBLECOLON(); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 96 "S1.lexer.lpp"
{ return S1::parser::make_COLON(); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 97 "S1.lexer.lpp"
{ return S1::parser::make_SEMICOLON(); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 98 "S1.lexer.lpp"
{ return S1::parser::make_INCREMENT(); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 99 "S1.lexer.lpp"
{ return S1::parser::make_DECREMENT(); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 100 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_LSHIFT(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 101 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_RSHIFT(); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 102 "S1.lexer.lpp"
{ return S1::parser::make_LSHIFT(); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 103 "S1.lexer.lpp"
{ return S1::parser::make_RSHIFT(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 104 "S1.lexer.lpp"
{ return S1::parser::make_OR(); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 105 "S1.lexer.lpp"
{ return S1::parser::make_AND(); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "S1.lexer.lpp"
{ return S1::parser::make_EQUALITY(); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "S1.lexer.lpp"
{ return S1::parser::make_INEQUALITY(); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "S1.lexer.lpp"
{ return S1::parser::make_LESS_EQUAL(); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 109 "S1.lexer.lpp"
{ return S1::parser::make_GREATER_EQUAL(); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 110 "S1.lexer.lpp"
{ return S1::parser::make_LESS(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 111 "S1.lexer.lpp"
{ return S1::parser::make_GREATER(); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 112 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_ADD(); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 113 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_SUB(); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 114 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_MULT(); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 115 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_DIV(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 116 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_MOD(); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 117 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_BITWISE_OR(); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 118 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_BITWISE_AND(); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 119 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN_BITWISE_EXOR(); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 120 "S1.lexer.lpp"
{ return S1::parser::make_ASSIGN(); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 121 "S1.lexer.lpp"
{ return S1::parser::make_ADD(); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 122 "S1.lexer.lpp"
{ return S1::parser::make_SUB(); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 123 "S1.lexer.lpp"
{ return S1::parser::make_MULT(); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 124 "S1.lexer.lpp"
{ return S1::parser::make_DIV(); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 125 "S1.lexer.lpp"
{ return S1::parser::make_MOD(); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 126 "S1.lexer.lpp"
{ return S1::parser::make_NOT(); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 127 "S1.lexer.lpp"
{ return S1::parser::make_COMPLEMENT(); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 128 "S1.lexer.lpp"
{ return S1::parser::make_BITWISE_OR(); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 129 "S1.lexer.lpp"
{ return S1::parser::make_BITWISE_AND(); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "S1.lexer.lpp"
{ return S1::parser::make_BITWISE_EXOR(); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 132 "S1.lexer.lpp"
{ return S1::parser::make_FILE(std::string(yytext)); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 133 "S1.lexer.lpp"
{ return S1::parser::make_NAME(utils::string::to_lower(yytext)); }
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 134 "S1.lexer.lpp"
{ return S1::parser::make_ISTRING(std::string(yytext).substr(1)); }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 135 "S1.lexer.lpp"
{ return S1::parser::make_STRING(std::string(yytext)); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 136 "S1.lexer.lpp"
{ return S1::parser::make_FLOAT(std::string(yytext)); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 137 "S1.lexer.lpp"
{ return S1::parser::make_INTEGER(std::string(yytext)); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_BLOCK_STATE):
case YY_STATE_EOF(DEVELOPER_BLOCK_STATE):
#line 139 "S1.lexer.lpp"
{ return S1::parser::make_S1EOF(); }
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 140 "S1.lexer.lpp"
{ throw S1::parser::syntax_error("invalid character: \'" + std::string(yytext) + "\' at line " + std::to_string(*pos)); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 141 "S1.lexer.lpp"
ECHO;
	YY_BREAK
#line 1793 "./S1/compiler_lexer.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 288 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 288 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 287);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 141 "S1.lexer.lpp"


